customCommands:
  - key: '<c-c>'
    description: 'Commit without verifying files'
    command: 'git commit -m "{{index .PromptResponses 0}}" --no-verify'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Commit Message'
        initialValue: ''
    loadingText: 'commiting without verifying files'
    subprocess: true

  - key: 'c'
    command: 'git cz'
    context: 'files'
    loadingText: 'opening commitizen commit tool'
    subprocess: true

keybinding:
  universal:
    scrollUpMain-alt1: '<c-k>'
    scrollDownMain-alt1: '<c-j>'
  files:
    commitChanges: 'C'

# To exit immediately if run outside of the Git repository
notARepository: 'quit'

# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  branchColors:
    # High contrast.
    main: magenta
    hotfix: red
    # Medium contrast.
    refactor: blue
    docs: cyan
    enh: green
    bug: yellow
    bugfix: yellow
    fix: yellow
    # Low contrast.
    feature: white bold
    # Very low contrast.
    "test-": white

  authorColors:
    DeadlySquad13: blue
    "Пакало Александр": yellow
    "Pakalo Alexander": yellow
    "*": green

  # Didn't find how to disable bold.
  theme:
    selectedLineBgColor:
      - underline
