customCommands:
  - key: '<c-c>'
    description: 'Commit without verifying files'
    command: 'git commit -m "{{index .PromptResponses 0}}" --no-verify'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'Commit Message'
        initialValue: ''
    loadingText: 'commiting without verifying files'
    subprocess: true

  - key: 'c'
    command: 'git cz'
    context: 'files'
    loadingText: 'opening commitizen commit tool'
    subprocess: true

keybinding:
  universal:
    scrollUpMain-alt1: '<c-k>'
    scrollDownMain-alt1: '<c-j>'
  files:
    commitChanges: 'C'

# To exit immediately if run outside of the Git repository
notARepository: 'quit'
